version: '3'
services:
  database:
    container_name: web-project-backend-database
    image: "postgres"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - web-project-backend-database:/var/lib/postgresql/data
volumes:
  web-project-backend-database:
